### ISSUE TITLE
How can I find if my devices is supported

### ISSUE THREAD

**Issue by guyluz11** [ctrysbita/miio-dart#2]
I want to buy Xiaomi light bulb and I want to know if I can use this package to control it.

Is there a place or a list that you can share with me?.

The name of the bulb is `Xiaomi Mi Smart LED Bulb Essential (White+Color)`.

**Comment by ctrysbita** [comment]
Normally u can control it if the bulb is using miio LAN protocol. This can be tested by sending a discover packet and you can do it by using built-in command line interface (CLI).

**Comment by guyluz11** [comment]
Hmm, so there is no list that you know of that shows all supported devices.
I guess that I will have to buy it and find out.

Thanks
