### ISSUE TITLE
More points by choosing a license 

### ISSUE THREAD

**Issue by guyluz11** [ctrysbita/miio-dart#6]
The current license of this package is not [OSI-approved license](https://opensource.org/licenses) so we are getting fewer pints on pub.dev

![image](https://user-images.githubusercontent.com/9304740/216770438-202a8947-1a98-495f-936c-0ecad4532be1.png)

**Comment by ctrysbita** [comment]
GPL is an OSI-approved license but pub didn't recognize it since we are using a markdown version :(
